### ISSUE TITLE
Councils's images are not been displayed.

### ISSUE THREAD

**Issue by navneet-28** [StudentsGymkhanaIITK/website#3]
![SGweb](https://user-images.githubusercontent.com/78998610/131240909-3d730d1d-efa8-468d-9589-0b3270677673.png)

**Comment by bhuvansingla** [comment]
The [website](https://students.iitk.ac.in/gymkhana/) is displaying the images fine for me. Can you provide more details about this issue, like which browser and version are you using?

**Comment by navneet-28** [comment]
This happens when I open the Github hosted [website](https://studentsgymkhanaiitk.github.io/website/).
On opening it through the domain that you provided in your comment, it works fine.

**Comment by bhuvansingla** [comment]
Oh okay. The GitHub Pages hosted website is no longer maintained. We used it during the initial phase of development of the website. Closing this issue.
